//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace sga.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DATOS_SCADAEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DATOS_SCADAEntities1 object using the connection string found in the 'DATOS_SCADAEntities1' section of the application configuration file.
        /// </summary>
        public DATOS_SCADAEntities1() : base("name=DATOS_SCADAEntities1", "DATOS_SCADAEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DATOS_SCADAEntities1 object.
        /// </summary>
        public DATOS_SCADAEntities1(string connectionString) : base(connectionString, "DATOS_SCADAEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DATOS_SCADAEntities1 object.
        /// </summary>
        public DATOS_SCADAEntities1(EntityConnection connection) : base(connection, "DATOS_SCADAEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id_line">No Metadata Documentation available.</param>
        public ObjectResult<llenar_combo_sistemas_Result> llenar_combo_sistemas(Nullable<global::System.Int32> id_line)
        {
            ObjectParameter id_lineParameter;
            if (id_line.HasValue)
            {
                id_lineParameter = new ObjectParameter("id_line", id_line);
            }
            else
            {
                id_lineParameter = new ObjectParameter("id_line", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<llenar_combo_sistemas_Result>("llenar_combo_sistemas", id_lineParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id_line">No Metadata Documentation available.</param>
        public ObjectResult<obtener_codigo_alarmas_Result> obtener_codigo_alarmas(Nullable<global::System.Int32> id_line)
        {
            ObjectParameter id_lineParameter;
            if (id_line.HasValue)
            {
                id_lineParameter = new ObjectParameter("id_line", id_line);
            }
            else
            {
                id_lineParameter = new ObjectParameter("id_line", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<obtener_codigo_alarmas_Result>("obtener_codigo_alarmas", id_lineParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id_line">No Metadata Documentation available.</param>
        /// <param name="term">No Metadata Documentation available.</param>
        public ObjectResult<obtener_descripcion_alarmas_Result> obtener_descripcion_alarmas(Nullable<global::System.Int32> id_line, global::System.String term)
        {
            ObjectParameter id_lineParameter;
            if (id_line.HasValue)
            {
                id_lineParameter = new ObjectParameter("id_line", id_line);
            }
            else
            {
                id_lineParameter = new ObjectParameter("id_line", typeof(global::System.Int32));
            }
    
            ObjectParameter termParameter;
            if (term != null)
            {
                termParameter = new ObjectParameter("term", term);
            }
            else
            {
                termParameter = new ObjectParameter("term", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<obtener_descripcion_alarmas_Result>("obtener_descripcion_alarmas", id_lineParameter, termParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id_line">No Metadata Documentation available.</param>
        /// <param name="term">No Metadata Documentation available.</param>
        public ObjectResult<obtener_direccion_alarmas_Result> obtener_direccion_alarmas(Nullable<global::System.Int32> id_line, global::System.String term)
        {
            ObjectParameter id_lineParameter;
            if (id_line.HasValue)
            {
                id_lineParameter = new ObjectParameter("id_line", id_line);
            }
            else
            {
                id_lineParameter = new ObjectParameter("id_line", typeof(global::System.Int32));
            }
    
            ObjectParameter termParameter;
            if (term != null)
            {
                termParameter = new ObjectParameter("term", term);
            }
            else
            {
                termParameter = new ObjectParameter("term", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<obtener_direccion_alarmas_Result>("obtener_direccion_alarmas", id_lineParameter, termParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id_line">No Metadata Documentation available.</param>
        public ObjectResult<llenar_combo_nodos_Result> llenar_combo_nodos(Nullable<global::System.Int32> id_line)
        {
            ObjectParameter id_lineParameter;
            if (id_line.HasValue)
            {
                id_lineParameter = new ObjectParameter("id_line", id_line);
            }
            else
            {
                id_lineParameter = new ObjectParameter("id_line", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<llenar_combo_nodos_Result>("llenar_combo_nodos", id_lineParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id_line">No Metadata Documentation available.</param>
        /// <param name="id_sistema">No Metadata Documentation available.</param>
        /// <param name="id_node">No Metadata Documentation available.</param>
        /// <param name="description">No Metadata Documentation available.</param>
        /// <param name="address">No Metadata Documentation available.</param>
        /// <param name="codigo">No Metadata Documentation available.</param>
        /// <param name="fechaInicio">No Metadata Documentation available.</param>
        /// <param name="fechaFin">No Metadata Documentation available.</param>
        /// <param name="view_events">No Metadata Documentation available.</param>
        /// <param name="view_prenorec">No Metadata Documentation available.</param>
        /// <param name="view_prerec">No Metadata Documentation available.</param>
        /// <param name="view_ausnorec">No Metadata Documentation available.</param>
        public ObjectResult<obtener_historico_alarmas_Result> obtener_historico_alarmas(Nullable<global::System.Int32> id_line, Nullable<global::System.Int32> id_sistema, global::System.String id_node, global::System.String description, global::System.String address, global::System.String codigo, Nullable<global::System.DateTime> fechaInicio, Nullable<global::System.DateTime> fechaFin, Nullable<global::System.Boolean> view_events, Nullable<global::System.Boolean> view_prenorec, Nullable<global::System.Boolean> view_prerec, Nullable<global::System.Boolean> view_ausnorec)
        {
            ObjectParameter id_lineParameter;
            if (id_line.HasValue)
            {
                id_lineParameter = new ObjectParameter("id_line", id_line);
            }
            else
            {
                id_lineParameter = new ObjectParameter("id_line", typeof(global::System.Int32));
            }
    
            ObjectParameter id_sistemaParameter;
            if (id_sistema.HasValue)
            {
                id_sistemaParameter = new ObjectParameter("id_sistema", id_sistema);
            }
            else
            {
                id_sistemaParameter = new ObjectParameter("id_sistema", typeof(global::System.Int32));
            }
    
            ObjectParameter id_nodeParameter;
            if (id_node != null)
            {
                id_nodeParameter = new ObjectParameter("id_node", id_node);
            }
            else
            {
                id_nodeParameter = new ObjectParameter("id_node", typeof(global::System.String));
            }
    
            ObjectParameter descriptionParameter;
            if (description != null)
            {
                descriptionParameter = new ObjectParameter("description", description);
            }
            else
            {
                descriptionParameter = new ObjectParameter("description", typeof(global::System.String));
            }
    
            ObjectParameter addressParameter;
            if (address != null)
            {
                addressParameter = new ObjectParameter("address", address);
            }
            else
            {
                addressParameter = new ObjectParameter("address", typeof(global::System.String));
            }
    
            ObjectParameter codigoParameter;
            if (codigo != null)
            {
                codigoParameter = new ObjectParameter("codigo", codigo);
            }
            else
            {
                codigoParameter = new ObjectParameter("codigo", typeof(global::System.String));
            }
    
            ObjectParameter fechaInicioParameter;
            if (fechaInicio.HasValue)
            {
                fechaInicioParameter = new ObjectParameter("fechaInicio", fechaInicio);
            }
            else
            {
                fechaInicioParameter = new ObjectParameter("fechaInicio", typeof(global::System.DateTime));
            }
    
            ObjectParameter fechaFinParameter;
            if (fechaFin.HasValue)
            {
                fechaFinParameter = new ObjectParameter("fechaFin", fechaFin);
            }
            else
            {
                fechaFinParameter = new ObjectParameter("fechaFin", typeof(global::System.DateTime));
            }
    
            ObjectParameter view_eventsParameter;
            if (view_events.HasValue)
            {
                view_eventsParameter = new ObjectParameter("view_events", view_events);
            }
            else
            {
                view_eventsParameter = new ObjectParameter("view_events", typeof(global::System.Boolean));
            }
    
            ObjectParameter view_prenorecParameter;
            if (view_prenorec.HasValue)
            {
                view_prenorecParameter = new ObjectParameter("view_prenorec", view_prenorec);
            }
            else
            {
                view_prenorecParameter = new ObjectParameter("view_prenorec", typeof(global::System.Boolean));
            }
    
            ObjectParameter view_prerecParameter;
            if (view_prerec.HasValue)
            {
                view_prerecParameter = new ObjectParameter("view_prerec", view_prerec);
            }
            else
            {
                view_prerecParameter = new ObjectParameter("view_prerec", typeof(global::System.Boolean));
            }
    
            ObjectParameter view_ausnorecParameter;
            if (view_ausnorec.HasValue)
            {
                view_ausnorecParameter = new ObjectParameter("view_ausnorec", view_ausnorec);
            }
            else
            {
                view_ausnorecParameter = new ObjectParameter("view_ausnorec", typeof(global::System.Boolean));
            }
    
            return base.ExecuteFunction<obtener_historico_alarmas_Result>("obtener_historico_alarmas", id_lineParameter, id_sistemaParameter, id_nodeParameter, descriptionParameter, addressParameter, codigoParameter, fechaInicioParameter, fechaFinParameter, view_eventsParameter, view_prenorecParameter, view_prerecParameter, view_ausnorecParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id_line">No Metadata Documentation available.</param>
        /// <param name="fechaInicio">No Metadata Documentation available.</param>
        /// <param name="fechaFin">No Metadata Documentation available.</param>
        /// <param name="intervalos">No Metadata Documentation available.</param>
        public ObjectResult<alarmas_cantidad_Result> alarmas_cantidad(Nullable<global::System.Int32> id_line, Nullable<global::System.DateTime> fechaInicio, Nullable<global::System.DateTime> fechaFin, Nullable<global::System.Int32> intervalos)
        {
            ObjectParameter id_lineParameter;
            if (id_line.HasValue)
            {
                id_lineParameter = new ObjectParameter("id_line", id_line);
            }
            else
            {
                id_lineParameter = new ObjectParameter("id_line", typeof(global::System.Int32));
            }
    
            ObjectParameter fechaInicioParameter;
            if (fechaInicio.HasValue)
            {
                fechaInicioParameter = new ObjectParameter("fechaInicio", fechaInicio);
            }
            else
            {
                fechaInicioParameter = new ObjectParameter("fechaInicio", typeof(global::System.DateTime));
            }
    
            ObjectParameter fechaFinParameter;
            if (fechaFin.HasValue)
            {
                fechaFinParameter = new ObjectParameter("fechaFin", fechaFin);
            }
            else
            {
                fechaFinParameter = new ObjectParameter("fechaFin", typeof(global::System.DateTime));
            }
    
            ObjectParameter intervalosParameter;
            if (intervalos.HasValue)
            {
                intervalosParameter = new ObjectParameter("intervalos", intervalos);
            }
            else
            {
                intervalosParameter = new ObjectParameter("intervalos", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<alarmas_cantidad_Result>("alarmas_cantidad", id_lineParameter, fechaInicioParameter, fechaFinParameter, intervalosParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="DATOS_SCADAModel", Name="alarmas_cantidad_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class alarmas_cantidad_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new alarmas_cantidad_Result object.
        /// </summary>
        /// <param name="x">Initial value of the x property.</param>
        /// <param name="y">Initial value of the y property.</param>
        /// <param name="z">Initial value of the z property.</param>
        public static alarmas_cantidad_Result Createalarmas_cantidad_Result(global::System.Int64 x, global::System.Int32 y, global::System.Int32 z)
        {
            alarmas_cantidad_Result alarmas_cantidad_Result = new alarmas_cantidad_Result();
            alarmas_cantidad_Result.x = x;
            alarmas_cantidad_Result.y = y;
            alarmas_cantidad_Result.z = z;
            return alarmas_cantidad_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 x
        {
            get
            {
                return _x;
            }
            set
            {
                OnxChanging(value);
                ReportPropertyChanging("x");
                _x = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("x");
                OnxChanged();
            }
        }
        private global::System.Int64 _x;
        partial void OnxChanging(global::System.Int64 value);
        partial void OnxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 y
        {
            get
            {
                return _y;
            }
            set
            {
                OnyChanging(value);
                ReportPropertyChanging("y");
                _y = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("y");
                OnyChanged();
            }
        }
        private global::System.Int32 _y;
        partial void OnyChanging(global::System.Int32 value);
        partial void OnyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 z
        {
            get
            {
                return _z;
            }
            set
            {
                OnzChanging(value);
                ReportPropertyChanging("z");
                _z = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("z");
                OnzChanged();
            }
        }
        private global::System.Int32 _z;
        partial void OnzChanging(global::System.Int32 value);
        partial void OnzChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="DATOS_SCADAModel", Name="llenar_combo_nodos_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class llenar_combo_nodos_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new llenar_combo_nodos_Result object.
        /// </summary>
        /// <param name="idNode">Initial value of the idNode property.</param>
        /// <param name="description">Initial value of the description property.</param>
        public static llenar_combo_nodos_Result Createllenar_combo_nodos_Result(global::System.String idNode, global::System.String description)
        {
            llenar_combo_nodos_Result llenar_combo_nodos_Result = new llenar_combo_nodos_Result();
            llenar_combo_nodos_Result.idNode = idNode;
            llenar_combo_nodos_Result.description = description;
            return llenar_combo_nodos_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idNode
        {
            get
            {
                return _idNode;
            }
            set
            {
                OnidNodeChanging(value);
                ReportPropertyChanging("idNode");
                _idNode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("idNode");
                OnidNodeChanged();
            }
        }
        private global::System.String _idNode;
        partial void OnidNodeChanging(global::System.String value);
        partial void OnidNodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="DATOS_SCADAModel", Name="llenar_combo_sistemas_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class llenar_combo_sistemas_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new llenar_combo_sistemas_Result object.
        /// </summary>
        /// <param name="idPlc">Initial value of the idPlc property.</param>
        /// <param name="description">Initial value of the description property.</param>
        public static llenar_combo_sistemas_Result Createllenar_combo_sistemas_Result(global::System.Int32 idPlc, global::System.String description)
        {
            llenar_combo_sistemas_Result llenar_combo_sistemas_Result = new llenar_combo_sistemas_Result();
            llenar_combo_sistemas_Result.idPlc = idPlc;
            llenar_combo_sistemas_Result.description = description;
            return llenar_combo_sistemas_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPlc
        {
            get
            {
                return _idPlc;
            }
            set
            {
                OnidPlcChanging(value);
                ReportPropertyChanging("idPlc");
                _idPlc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idPlc");
                OnidPlcChanged();
            }
        }
        private global::System.Int32 _idPlc;
        partial void OnidPlcChanging(global::System.Int32 value);
        partial void OnidPlcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="DATOS_SCADAModel", Name="obtener_codigo_alarmas_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class obtener_codigo_alarmas_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String alarm
        {
            get
            {
                return _alarm;
            }
            set
            {
                OnalarmChanging(value);
                ReportPropertyChanging("alarm");
                _alarm = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("alarm");
                OnalarmChanged();
            }
        }
        private global::System.String _alarm;
        partial void OnalarmChanging(global::System.String value);
        partial void OnalarmChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="DATOS_SCADAModel", Name="obtener_descripcion_alarmas_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class obtener_descripcion_alarmas_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="DATOS_SCADAModel", Name="obtener_direccion_alarmas_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class obtener_direccion_alarmas_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="DATOS_SCADAModel", Name="obtener_historico_alarmas_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class obtener_historico_alarmas_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new obtener_historico_alarmas_Result object.
        /// </summary>
        /// <param name="estado">Initial value of the estado property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="timeOn">Initial value of the timeOn property.</param>
        /// <param name="timeOff">Initial value of the timeOff property.</param>
        /// <param name="timeAcknowledge">Initial value of the timeAcknowledge property.</param>
        /// <param name="timeReset">Initial value of the timeReset property.</param>
        /// <param name="timeQuarantine">Initial value of the timeQuarantine property.</param>
        /// <param name="event">Initial value of the event property.</param>
        /// <param name="eventDescription">Initial value of the eventDescription property.</param>
        /// <param name="node">Initial value of the node property.</param>
        /// <param name="idAlarm">Initial value of the idAlarm property.</param>
        /// <param name="timeStampOn">Initial value of the timeStampOn property.</param>
        public static obtener_historico_alarmas_Result Createobtener_historico_alarmas_Result(global::System.String estado, global::System.String description, global::System.String timeOn, global::System.String timeOff, global::System.String timeAcknowledge, global::System.String timeReset, global::System.String timeQuarantine, global::System.String @event, global::System.String eventDescription, global::System.String node, global::System.Int32 idAlarm, global::System.Int64 timeStampOn)
        {
            obtener_historico_alarmas_Result obtener_historico_alarmas_Result = new obtener_historico_alarmas_Result();
            obtener_historico_alarmas_Result.estado = estado;
            obtener_historico_alarmas_Result.description = description;
            obtener_historico_alarmas_Result.timeOn = timeOn;
            obtener_historico_alarmas_Result.timeOff = timeOff;
            obtener_historico_alarmas_Result.timeAcknowledge = timeAcknowledge;
            obtener_historico_alarmas_Result.timeReset = timeReset;
            obtener_historico_alarmas_Result.timeQuarantine = timeQuarantine;
            obtener_historico_alarmas_Result.@event = @event;
            obtener_historico_alarmas_Result.eventDescription = eventDescription;
            obtener_historico_alarmas_Result.node = node;
            obtener_historico_alarmas_Result.idAlarm = idAlarm;
            obtener_historico_alarmas_Result.timeStampOn = timeStampOn;
            return obtener_historico_alarmas_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String timeOn
        {
            get
            {
                return _timeOn;
            }
            set
            {
                OntimeOnChanging(value);
                ReportPropertyChanging("timeOn");
                _timeOn = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("timeOn");
                OntimeOnChanged();
            }
        }
        private global::System.String _timeOn;
        partial void OntimeOnChanging(global::System.String value);
        partial void OntimeOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String timeOff
        {
            get
            {
                return _timeOff;
            }
            set
            {
                OntimeOffChanging(value);
                ReportPropertyChanging("timeOff");
                _timeOff = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("timeOff");
                OntimeOffChanged();
            }
        }
        private global::System.String _timeOff;
        partial void OntimeOffChanging(global::System.String value);
        partial void OntimeOffChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String timeAcknowledge
        {
            get
            {
                return _timeAcknowledge;
            }
            set
            {
                OntimeAcknowledgeChanging(value);
                ReportPropertyChanging("timeAcknowledge");
                _timeAcknowledge = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("timeAcknowledge");
                OntimeAcknowledgeChanged();
            }
        }
        private global::System.String _timeAcknowledge;
        partial void OntimeAcknowledgeChanging(global::System.String value);
        partial void OntimeAcknowledgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String timeReset
        {
            get
            {
                return _timeReset;
            }
            set
            {
                OntimeResetChanging(value);
                ReportPropertyChanging("timeReset");
                _timeReset = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("timeReset");
                OntimeResetChanged();
            }
        }
        private global::System.String _timeReset;
        partial void OntimeResetChanging(global::System.String value);
        partial void OntimeResetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String timeQuarantine
        {
            get
            {
                return _timeQuarantine;
            }
            set
            {
                OntimeQuarantineChanging(value);
                ReportPropertyChanging("timeQuarantine");
                _timeQuarantine = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("timeQuarantine");
                OntimeQuarantineChanged();
            }
        }
        private global::System.String _timeQuarantine;
        partial void OntimeQuarantineChanging(global::System.String value);
        partial void OntimeQuarantineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String @event
        {
            get
            {
                return _event;
            }
            set
            {
                OneventChanging(value);
                ReportPropertyChanging("event");
                _event = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("event");
                OneventChanged();
            }
        }
        private global::System.String _event;
        partial void OneventChanging(global::System.String value);
        partial void OneventChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String eventDescription
        {
            get
            {
                return _eventDescription;
            }
            set
            {
                OneventDescriptionChanging(value);
                ReportPropertyChanging("eventDescription");
                _eventDescription = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("eventDescription");
                OneventDescriptionChanged();
            }
        }
        private global::System.String _eventDescription;
        partial void OneventDescriptionChanging(global::System.String value);
        partial void OneventDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String node
        {
            get
            {
                return _node;
            }
            set
            {
                OnnodeChanging(value);
                ReportPropertyChanging("node");
                _node = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("node");
                OnnodeChanged();
            }
        }
        private global::System.String _node;
        partial void OnnodeChanging(global::System.String value);
        partial void OnnodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idAlarm
        {
            get
            {
                return _idAlarm;
            }
            set
            {
                OnidAlarmChanging(value);
                ReportPropertyChanging("idAlarm");
                _idAlarm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idAlarm");
                OnidAlarmChanged();
            }
        }
        private global::System.Int32 _idAlarm;
        partial void OnidAlarmChanging(global::System.Int32 value);
        partial void OnidAlarmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 timeStampOn
        {
            get
            {
                return _timeStampOn;
            }
            set
            {
                OntimeStampOnChanging(value);
                ReportPropertyChanging("timeStampOn");
                _timeStampOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("timeStampOn");
                OntimeStampOnChanged();
            }
        }
        private global::System.Int64 _timeStampOn;
        partial void OntimeStampOnChanging(global::System.Int64 value);
        partial void OntimeStampOnChanged();

        #endregion
    }

    #endregion
    
}
